env:
    browser: true
    es6: true
extends:
    - airbnb
    - plugin:prettier/recommended
parserOptions:
    ecmaFeatures: { jsx: true }
    ecmaVersion: 2020
    sourceType: module
rules:
    import/extensions: [error, ignorePackages]
    import/no-extraneous-dependencies: [error, { packageDir: '.' }]
    react/prop-types: off
    jsx-a11y/label-has-associated-control: off
